//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Vacations = new ObservableListSource<Vacation>();
            this.WorkingHours = new ObservableListSource<WorkingHour>();
        }
    
        public string employee_id { get; set; }
        public string passport_id { get; set; }
        public string position_id { get; set; }
        public string department_id { get; set; }
        public Nullable<System.DateTime> start_work { get; set; }
        public Nullable<System.DateTime> end_work { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Pasport_data Pasport_data { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Vacation> Vacations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<WorkingHour> WorkingHours { get; set; }
    }
}
