//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        public string vacation_id { get; set; }
        public string employee_id { get; set; }
        public Nullable<System.DateTime> vacation_start { get; set; }
        public Nullable<System.DateTime> vacation_end { get; set; }
        public Nullable<decimal> vacation_payment { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
