//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingHour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkingHour()
        {
            this.Salary_issuance = new ObservableListSource<Salary_issuance>();
        }
    
        public int Id { get; set; }
        public string employee_id { get; set; }
        public Nullable<int> hour_count { get; set; }
        public Nullable<int> overtime_hours_count { get; set; }
        public Nullable<int> day_off_hours_count { get; set; }
        public Nullable<System.DateTime> salary_date { get; set; }
        public Nullable<decimal> salary { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Salary_issuance> Salary_issuance { get; set; }
    }
}
